#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Go Lang
#

export GOHOME="$HOME/go"
export GOPATH="$HOME/go"
export GOROOT="/usr/lib/go"

PATH="$GOPATH/bin:$PATH"

#
# NPM
#

export NVM_DIR="$HOME/.nvm"
# Load NVM if available
if [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"

  nvm use default > /dev/null
else
  export NPM_PACKAGES="$HOME/.local/share/npm"
  export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"
  export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"

  PATH="$NPM_PACKAGES/bin:$PATH"
fi

export GOPATH="$HOME/Development/go"
export GOROOT="/usr/lib/golang"

export PATH="$GOPATH/bin/:$PATH"

#
# Tools
#

PATH="$HOME/Tools/bin:$PATH"

# Load local zshenv
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/local/zshenv.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/local/zshenv.local"
fi
