#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Load local zshrc
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/local/zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/local/zshrc.local"
fi

# Key bindings for IntelliJ
bindkey '\e[H' beginning-of-line
bindkey '\e[F' end-of-line
